### ISSUE TITLE
HaveRight using Kodi ?

### ISSUE THREAD

**Issue by Pierre-Gilles** [Time-Lords/gladys-cron#1]
Hi!

I'm using your module, and when I'm trying to reach the route /cron/destroy, I have a 500 error because of the use of "KodiDevice" here : https://github.com/Time-Lords/gladys-cron/blob/master/controllers/CronController.js#L11 . I supposed it's a little mistake, it's suppose to be "CronRule.findOne" :) 

Otherwise very useful module !

**Comment by Time-Lords** [comment]
Hi,

Thanks, fixed :)
